### ISSUE TITLE
Cannot install snowcrash.

### ISSUE THREAD

**Issue by mengheangrat** [the-hypermedia-project/representor-swift#34]
brew install --HEAD https://raw.github.com/apiaryio/snowcrash/master/tools/homebrew/snowcrash.rb

curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing: /usr/bin/curl --remote-time --location --user-agent Homebrew/1.1.10\ (Macintosh;\ Intel\ macOS\ 10.12.2)\ curl/7.51.0 --progress-bar --fail https://raw.github.com/apiaryio/snowcrash/master/tools/homebrew/snowcrash.rb -o /Users/ratmengheang/Library/Caches/Homebrew/Formula/snowcrash.rb

**Comment by kylef** [comment]
For any support for Snowcrash, you should report them in the snow crash issue tracker over at https://github.com/apiaryio/snowcrash/issues.

That said, Snowcrash command line tool was replaced by Drafter. See https://github.com/apiaryio/drafter#install for installation instructions.
